### ISSUE TITLE
Update Contributing.md with this text

### ISSUE THREAD

**Issue by RaoOfPhysics** [j-joe-akin/fig-can#1]
``` markdown
# For graphic designers

1. We need a FigureCanvas logo; click here for inspirations.

# For UX specialists

1. We need a mockup of 5 figures with 8 related parameter/value pairs listed for each figure. Figures will share a majority of the same parameters; some figures will share only a few; some parameters will only be listed for 1 figure.

# For project managers

1. Please review our ROADMAP

# For developers

1. Create “sandbox” in browser window/tab which accepts image files by drag-and-drop from another page (import)
2. Upon drag and drop other nearby information is collected and displayed along with figure as an additional object
3. Test “sandbox” functionality with images imported from a variety of open science repositories; click here for a list of open science, single-figure repositories
```

**Comment by j-joe-akin** [comment]
Did it! Thanks RaoOfPhysics (Achintya, right?), the bold text looks a lot better. Do you know if there is a way to link to a specific part of the page, from a .md file to a .md file. So, when contributors click on the link in README, it takes them to that section in the CONTRIBUTING?

**Comment by RaoOfPhysics** [comment]
Happy to help! (And yes, it's Achintya.)

If you hover over the `.md` file as displayed in GH's web interface, you'll see little anchor tags pop up. You can use them to link directly to a section header. In your case:
- https://github.com/j-joe-akin/fig-can/blob/master/CONTRIBUTING.md#for-graphic-designers
- https://github.com/j-joe-akin/fig-can/blob/master/CONTRIBUTING.md#for-ux-specialists
- https://github.com/j-joe-akin/fig-can/blob/master/CONTRIBUTING.md#for-project-managers
- https://github.com/j-joe-akin/fig-can/blob/master/CONTRIBUTING.md#for-developers

If you want, I can fork your repo and edit the README accordingly. Let me know!

**Comment by RaoOfPhysics** [comment]
(For reference, this issue was closed with commit https://github.com/j-joe-akin/fig-can/commit/061ce269609c62fa4ccdd7194900c0d5e68e9165)

You can reference an issue, PR or user in your commit message and GH will do all the relevant linking. Super-useful to automatically close issues when your edits are merged etc.

**Comment by j-joe-akin** [comment]
Thanks for the tip! So when I commit, just mention the name, or issue in
the commit message? What is PR?

You can certainly fork and edit. Thanks Achintya.

**Comment by RaoOfPhysics** [comment]
To mention a user, you would tag their GH handle (so, `@RaoOfPhysics` in my case). You can reference an issue with a hashtag (so, this issue would be `#1`) and use [certain keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) to close the issue. You can also say `addresses #1` if the issue is not closed by the commit but merely addressed by it.

A PR is a Pull Request. You'll have to see your first when I make my changes -- you will be asked to merge my changes into your document! Coming up later today!
