### ISSUE TITLE
Some suggested changes

### ISSUE THREAD

**Issue by gg927** [j-joe-akin/fig-can#5]
Joe in the readme, perhaps we use the phrase "version control for science". I don't think that the problem of reproducibility has been defined. "Traditional publishing only allows the first guy on the scene to publish their data. Later versions whether they reproduce the findings or not are suppressed, leading to major crises in healthcare"

In the contributor section: the 8 parameters/variables are not quite clear

And for the developer and UX both, I think this point could be valuable
-Human Centered Design: Figures come in all shapes and sizes. Where they are placed on the page and relative to each other can bias their visualization and the ease of understanding their data.

**Comment by gg927** [comment]
Also, I think a mockup of the figure Canvas in the same image, highlighting the ease of view would be useful. The "product" ideation is not well defined.

**Comment by j-joe-akin** [comment]
Added mockup and links.
